### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by mfkdso** [BuiltBrokenModding/ICBM#140] opened 2016-02-19 08:30 UTC
http://pastebin.com/GwVaPh5j

Happens with no other mods installed. Tried with multiple versions of both VoltzEngine and ICBM. Asks if I want to download codinglib.

**Comment by DarkGuardsman** [comment] 2016-02-19 11:42
Looks like it failed to download coding lib automaticly. Make sure your using the latest version of VoltzEngine. If you are try manually downloading coding lib from http://api.dmodoomsirius.me/com/builtbroken/codinglib/CodingLib/ . If you do this and it doesn't work change the file name's version # to 0.0.3b27 for coding lib. This should fix the issue for the moment. I'll bug @dmodoomsirius and see why its asking for a file that does not exist.

**Comment by dmodoomsirius** [comment] 2016-02-19 20:38
try updating to a newer build. you are using a older build. we are up to 0.9.2 and you are using 0.7.2b188.

**Comment by dmodoomsirius** [comment] 2016-02-21 05:12
Closing as it is a duplicate of https://github.com/BuiltBrokenModding/VoltzEngine/issues/30 will update here.

**Closed by dmodoomsirius** 2016-02-21 05:12 UTC
Labels: Bug, high priority, Investigating
