### ISSUE TITLE
Infinite Tick Loop from Multiblock Error (Silos)

### ISSUE THREAD

**Issue by NikonJR** [BuiltBrokenModding/ICBM#304] opened 2017-07-15 22:25 UTC
https://pastebin.com/6eyn28V2

The missile silos are creating an error message in console and creating massive lag as a result. Removing the items does work, but I would like to figure out what the problem is. 
Pastebin is the relevant log, .zip contains whole .txt.
[fml-server-latest.zip](https://github.com/BuiltBrokenModding/ICBM/files/1150676/fml-server-latest.zip)

**Comment by NikonJR** [comment] 2017-08-13 01:51
I would like it if you took game-breaking bugs such as this more seriously. It's been a month.  At the very least, a reply signifying you acknowledge the bug's existence would be appreciated.  @DarkGuardsman  I realize that this might just be a hobby of yours and you might have a full-time job, but please help your users out.

**Comment by DarkGuardsman** [comment] 2017-08-13 04:48
If I'm not mistaken the issue was actually solved a while ago in VoltzEngine. It just seems I never got around to closing the ticket or replying. This normally doesn't happen but no point worrying about that. If you want you can download the latest files to see if the problem is gone. 

https://minecraft.curseforge.com/projects/voltz-engine/files/2462412
https://minecraft.curseforge.com/projects/icbm/files/2461337

Both of those were recently testing in single player using MultiMC without any major problems. Though I do admit I only lightly tested due to time demand. As well I need to do a pass with server testing. However, I suspect it should work for the most part.

Additionally, after I'm done with the rewrite for the pre-1.12 update I will do another testing pass. At this point, I should catch most of the issue still in the mod.

**Closed as completed** 2018-01-04 22:14 UTC
